[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "airport-traffic-analyzer"
version = "0.1.0"
requires-python = ">= 3.12.4"
description = "A real-time dashboard for monitoring airport traffic and airline delays."
dependencies = [
    "pandas",
    "requests",
    "scikit-learn",
    "openmeteo-requests"
]

[tool.setuptools]
packages = ["scripts"]